export default {
  bug: 'src/assets/types/bug.svg',
  dark: 'src/assets/types/dark.svg',
  dragon: 'src/assets/types/dragon.svg',
  electric: 'src/assets/types/electric.svg',
  fairy: 'src/assets/types/fairy.svg',
  fighting: 'src/assets/types/fighting.svg',
  fire: 'src/assets/types/fire.svg',
  flying: 'src/assets/types/flying.svg',
  ghost: 'src/assets/types/ghost.svg',
  grass: 'src/assets/types/grass.svg',
  ground: 'src/assets/types/ground.svg',
  ice: 'src/assets/types/ice.svg',
  normal: 'src/assets/types/normal.svg',
  poison: 'src/assets/types/poison.svg',
  psychic: 'src/assets/types/psychic.svg',
  rock: 'src/assets/types/rock.svg',
  steel: 'src/assets/types/steel.svg',
  water: 'src/assets/types/water.svg',
};
